src/DevSkill.Inventory/DevSkill.Inventory.Web/Areas/Admin/Controllers/StockTransferController.cs
using DevSkill.Inventory.Application.Services;
using DevSkill.Inventory.Web.Areas.Admin.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Data;
using System.Web;

namespace DevSkill.Inventory.Web.Areas.Admin.Controllers
{
    [Area("Admin"), Authorize]
    public class StockTransferController : Controller
    {
        private readonly IStockTransferManagementService _stockTransferManagementService;
        private readonly IStockItemManagementService _stockItemManagementService;
        private readonly ILogger<StockTransferController> _logger;
        private readonly IItemManagementService _itemManagementService;
        private readonly IWarehouseManagementService _warehouseManagementService;

        public StockTransferController(ILogger<StockTransferController> logger,
            IStockTransferManagementService stockTransferManagementService,
            IStockItemManagementService stockItemManagementService,
            IItemManagementService itemManagementService,
            IWarehouseManagementService warehouseManagementService)
        {
            _logger = logger;
            _stockTransferManagementService = stockTransferManagementService;
            _stockItemManagementService = stockItemManagementService;
            _itemManagementService = itemManagementService;
            _warehouseManagementService = warehouseManagementService;
        }

        [Authorize(Roles = "SalesPerson,Admin")]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost, Authorize(Roles = "SalesPerson,Admin")]
        public async Task<JsonResult> GetStockTransferJsonData([FromBody] StockTransferListModel model)
        {
            try
            {
                var result = await _stockTransferManagementService.GetStockTransfersAsync(
                    model.PageIndex,
                    model.PageSize,
                    model.Search,
                    model.FormatSortExpression("TransferDate", "SourceWarehouse", "DestinationWarehouse", "Item", "Quantity", "Note")
                );

                var stockTransferJsonData = new
                {
                    recordsTotal = result.total,
                    recordsFiltered = result.totalDisplay,
                    data = result.data.Select(record => new string[]
                    {
                       record.TransferDate.ToString("yyyy-MM-dd HH:mm:ss"),
                       HttpUtility.HtmlEncode (record.SourceWarehouse?.Name ?? "N/A"),
                       HttpUtility.HtmlEncode (record.DestinationWarehouse?.Name ?? "N/A"),
                       HttpUtility.HtmlEncode(record.Item?.Name ?? "No Item"),
                       record.Quantity.ToString(),
                       HttpUtility.HtmlEncode( record.Note ?? "N/A"),
                       record.Id.ToString()
                    }).ToArray()
                };
                return Json(stockTransferJsonData);
            }
            catch (Exception ex)
            {
                _logger.LogError($"Error fetching stock transfer data: {ex.Message}");

                return Json(new { success = false, message = "Error fetching stock transfer data. Please try again." });
            }
        }

        [HttpGet]
        public async Task<JsonResult> GetItemsByWarehouse(Guid warehouseId)
        {
            try
            {
                var stockItems = await _stockItemManagementService.GetStockItemsAsyncByWarehouse(warehouseId);
                var items = stockItems.Select(si => new
                {
                    id = si.ItemId,
                    name = si.Item.Name,
                    quantity = si.Quantity
                });

                return Json(items);
            }
            catch (Exception ex)
            {
                _logger.LogError($"Error fetching items for warehouse {warehouseId}: {ex.Message}");
                return Json(new { success = false, message = "Error fetching items. Please try again." });
            }
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create()
        {
            var model = new StockTransferCreateModel();
            await PopulateStockTransferDropdownsAsync(model);
            return View(model);
        }

        [HttpPost, ValidateAntiForgeryToken, Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create(StockTransferCreateModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await _stockTransferManagementService.TransferStockAsync(
                        model.ItemId, model.SourceWarehouseId, model.DestinationWarehouseId, model.TransferQuantity, model.Notes);

                    TempData["SuccessMessage"] = "Stock transferred successfully!";
                    return RedirectToAction("Index");
                }
                catch (ArgumentException ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
                catch (InvalidOperationException ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", "An unexpected error occurred: " + ex.Message);
                }
            }
            await PopulateStockTransferDropdownsAsync(model);
            return View(model);
        }


        private async Task PopulateStockTransferDropdownsAsync(StockTransferCreateModel model)
        {
            model.Warehouses = (await _warehouseManagementService.GetWarehousesAsync())
                .Select(w => new SelectListItem
                {
                    Value = w.Id.ToString(),
                    Text = w.Name
                }).ToList();

            model.Items = (await _itemManagementService.GetItemsAsync())
                .Select(i => new SelectListItem
                {
                    Value = i.Id.ToString(),
                    Text = i.Name
                }).ToList();
        }


        [HttpPost, ValidateAntiForgeryToken, Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteTransfer(Guid id)
        {
            await _stockTransferManagementService.DeleteTransferAsync(id);
            return Json(new { success = true, message = "Transfer deleted successfully." });
        }
    }
}

src/DevSkill.Inventory/DevSkill.Inventory.Web/Areas/Admin/Views/StockTransfer/Create.cshtml
@model StockTransferCreateModel

@{
	ViewData["Title"] = "Create Transfer";
}
<link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet" />
<section class="content">

	<div class="card card-info">
		<div class="card-header">
			<h3 class="card-title">Create StockTransfer</h3>
		</div>
		<div class="card-body">
			<form asp-antiforgery="true" asp-area="Admin" asp-controller="StockTransfer" asp-action="Create">
				<div class="row">
					<div class="col-md-3">
						<div class="form-group">
							<input type="datetime-local" class="form-control" id="Date" name="Date" value="@Model.TransferDate.ToString("yyyy-MM-ddTHH:mm")" />
							<span asp-validation-for="TransferDate" class="text-danger"></span>
						</div>
					</div>
					<div class=" col-md-4">
						<div class="form-group">
							<select asp-for="SourceWarehouseId" class="form-control" asp-items="Model.Warehouses" id="sourceWarehouseSelect">
								<option value="">Warehouse From</option>
							</select>
							<span asp-validation-for="SourceWarehouseId" class="text-danger"></span>
						</div>
					</div>

					<div class=" col-md-4">
						<div class="form-group">
							<select asp-for="DestinationWarehouseId" class="form-control" asp-items="Model.Warehouses" id="destinationWarehouseSelect">
								<option value="">Warehouse To</option>
							</select>
							<span asp-validation-for="DestinationWarehouseId" class="text-danger"></span>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-md-4">
						<div class="form-group">
							<label asp-for="ItemId" class="control-label">Item</label>
							<select asp-for="ItemId" class="form-control" id="itemSelect">
								<option value="">Select Item</option>
							</select>
							<span asp-validation-for="ItemId" class="text-danger"></span>
						</div>
					</div>
					<div class="col-md-4">
						<div class="form-group">
							<label asp-for="TransferQuantity" class="control-label">Transfer Quantity</label>
							<input asp-for="TransferQuantity" class="form-control" />
							<span asp-validation-for="TransferQuantity" class="text-danger"></span>
						</div>
					</div>
				</div>

				<div class="row">
					<div class="col-sm-12">
						<div class="form-group">
							<label asp-for="Notes" class="control-label">Notes</label>
							<textarea asp-for="Notes" class="form-control"></textarea>
							<span asp-validation-for="Notes" class="text-danger"></span>
						</div>
					</div>
				</div>
				<button type="submit" class="btn btn-info btn-flat">Submit</button>
				<a asp-action="Index" class="btn btn-danger">Cancel</a>
			</form>
		</div>
	</div>
</section>

@section Scripts {
	<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
	<script>
		$(document).ready(function () {


			$('#sourceWarehouseSelect').on('change', function () {
				const warehouseId = $(this).val();
				const itemSelect = $('#itemSelect');
				itemSelect.empty().append('<option value="">Select Item</option>'); // Clear previous items

				if (warehouseId) {
					$('#additionalFields').show();

					// Fetch items based on the selected warehouse
					$.ajax({
						url: '@Url.Action("GetItemsByWarehouse", "StockTransfer")',
						type: 'GET',
						data: { warehouseId: warehouseId },
						success: function (data) {
							if (data.length > 0) {
								$.each(data, function (index, item) {
									itemSelect.append($('<option></option>').val(item.id).text(item.name + ' (Qty: ' + item.quantity + ')'));
								});
							} else {
								itemSelect.append('<option value="">No items found</option>');
							}
						},
						error: function () {
							itemSelect.append('<option value="">Error fetching items</option>');
						}
					});
				} else {
					$('#additionalFields').hide();
				}
			});

			$('#destinationWarehouseSelect').on('change', validateWarehouses);
			$('#sourceWarehouseSelect').on('change', validateWarehouses);

			$('#stockTransferForm').on('submit', function (e) {
				if (!validateWarehouses()) {
					e.preventDefault(); // Prevent form submission if validation fails
				}
			});

			function validateWarehouses() {
				const sourceWarehouseId = $('#sourceWarehouseSelect').val();
				const destinationWarehouseId = $('#destinationWarehouseSelect').val();

				if (sourceWarehouseId && destinationWarehouseId && sourceWarehouseId === destinationWarehouseId) {
					showToast('Source and Destination warehouses cannot be the same.', 'error');
					return false;
				}
				return true;
			}

			function showToast(message, type) {
				if (type === 'error') {
					toastr.error(message);
				} else {
					toastr.success(message); // You can customize success messages as well
				}
			}
		});

		// You might want to add server-side error handling to show Toastr notifications here
		@if (ViewData.ModelState.IsValid == false)
		{
			var errors = ViewData.ModelState.Values.SelectMany(v => v.Errors.Select(e => e.ErrorMessage));
			foreach (var error in errors)
			{
				<text>showToast('@error', 'error'); </text>
			}
		}
	</script>

	@{
		await Html.RenderPartialAsync("_ValidationScriptsPartial");
	}
}

src/DevSkill.Inventory/DevSkill.Inventory.Web/Areas/Admin/Views/StockTransfer/Index.cshtml
@model StockTransferListModel

@{
	ViewData["Title"] = "Index";
}

@section Styles
{
	<!-- Include the necessary DataTable CSS files -->
	<link rel="stylesheet" href="~/adminlte/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
	<link rel="stylesheet" href="~/adminlte/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
	<link rel="stylesheet" href="~/adminlte/plugins/datatables-buttons/css/buttons.bootstrap4.min.css">
	<link rel="stylesheet" href="~/css/custom.css" />

	<link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet" />
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
}

@section Scripts
{
	<script src="~/adminlte/plugins/datatables/jquery.dataTables.min.js"></script>
	<script src="~/adminlte/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
	<script src="~/adminlte/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
	<script src="~/adminlte/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
	<script src="~/adminlte/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
	<script src="~/adminlte/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
	<script src="~/adminlte/plugins/jszip/jszip.min.js"></script>
	<script src="~/adminlte/plugins/pdfmake/pdfmake.min.js"></script>
	<script src="~/adminlte/plugins/pdfmake/vfs_fonts.js"></script>
	<script src="~/adminlte/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
	<script src="~/adminlte/plugins/datatables-buttons/js/buttons.print.min.js"></script>
	<script src="~/adminlte/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

	<script>
		$(function () {
			var table = $("#stockTransfers").DataTable({
				processing: true,
				serverSide: true,
				responsive: true,
				searching: true,
				lengthChange: true,
				autoWidth: false,
				lengthMenu: [
					[10, 25, 50, -1],
					[10, 25, 50, 'All']
				],
				ajax: {
					url: "/Admin/StockTransfer/GetStockTransferJsonData",
					type: "POST",
					contentType: "application/json",
					dataType: "json",
					data: function (d) {
						return JSON.stringify(d); // Send DataTable parameters
					},
				},
				columnDefs: [
					{
						orderable: false,
						targets: 6, // Disable sorting on the Action column
						render: function (data, type, row) {
							return `
												<button type="button" class="btn btn-outline-danger btn-sm show-bs-modal" data-id='${data}'>
													<i class="fas fa-trash"></i> <!-- Delete icon -->
												</button>
											`;
						}
					}
				],
				dom: '<"top">rt<"bottom"il><"clear">',
				language: {
					lengthMenu: "Items per page: _MENU_"
				},
				infoCallback: function (settings, start, end, max, total, pre) {
					return `Total Transfer: ${total}`;
				},
				ordering: true,
				order: [],
			});

			// Show confirmation modal for delete
			$('#stockTransfers').on('click', '.show-bs-modal', function (event) {
				let id = $(this).data("id");
				let modal = $("#modal-default");
				modal.find('.modal-body p').text('Do you confirm to delete this?');
				$("#deleteId").val(id); // Assign the ID to the hidden field
				$("#deleteForm").attr("action", "/admin/stockTransfer/DeleteTransfer");
				modal.modal('show');
			});

			$("#deleteButton").click(function (event) {
				event.preventDefault();  // Prevent the form from submitting normally

				var form = $("#deleteForm");
				var actionUrl = form.attr('action');
				var id = $("#deleteId").val();  // Get the ID from the hidden input field

				$.ajax({
					url: actionUrl,
					method: "POST",
					data: {
						id: id,
						__RequestVerificationToken: $('input[name="__RequestVerificationToken"]').val()  // Pass the anti-forgery token
					},
					success: function (response) {
						if (response.success) {
							toastr.success(response.message);  // Show success message
							$('#modal-default').modal('hide');  // Close the modal
							table.ajax.reload(null, false);  // Reload the DataTable without resetting pagination
							$('#stockTransfers_processing').hide();  // Hide processing message manually if needed
						} else {
							toastr.error("An error occurred while deleting the service.");
						}
					},
					error: function () {
						toastr.error("An error occurred while processing the request.");
					}
				});
			});

		@if (TempData["SuccessMessage"] != null)
		{
			<text>
					toastr.success('@TempData["SuccessMessage"]');
			</text>
		}
				});
	</script>
}

<section class="content-header">
	<div class="container-fluid">
		<div class="row mb-2">
			<div class="col-sm-6">
				<h4>Stock Transfer</h4>
			</div>
			<div class="col-sm-6">
				<ol class="breadcrumb float-sm-right">
					<li class="breadcrumb-item">
						<a class="btn btn-info float-sm-right ml-2" asp-area="Admin" asp-controller="StockTransfer" asp-action="Create">
							+Add
						</a>
					</li>
				</ol>
			</div>
		</div>
	</div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">
	<div class="card card-info">
		<div class="card-body">
			<partial name="_ResponsePartial" />
			<partial name="_ModalPartial" />
			<table id="stockTransfers" class="table table-bordered table-striped custom-table">
				<thead>
					<tr>
						<th>Date</th>
						<th>From</th>
						<th>To</th>
						<th>Item Name</th>
						<th>Transferred Quantity</th>
						<th>Note</th>
						<th class="text-right">Action</th>
					</tr>
				</thead>
				<tbody>
					<!-- Table rows will be dynamically generated by DataTable AJAX call -->
				</tbody>
			</table>
		</div>
	</div>
</section>